// <auto-generated />
namespace Musique.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _201704101220574_Comments1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201704101220574_Comments1));
        
        string IMigrationMetadata.Id
        {
            get { return "201704101244502_201704101220574_Comments1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
